from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import date
import controladores.Register
from controladores.Register import *
from modelos.tabla_inventario import *




class Ui_VENTANA(object):
    def setupUi(self, VENTANA):
        self.modelo_principal = ModeloPrincipal()
        self.registrar = RegistrarInventario()
        VENTANA.setObjectName("VENTANA")
        VENTANA.setEnabled(True)
        VENTANA.resize(859, 728)
        font = QtGui.QFont()
        font.setPointSize(9)
        VENTANA.setFont(font)
        self.centralwidget = QtWidgets.QWidget(VENTANA)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 45, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 40, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 40, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 40, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 50, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(650, 50, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.nom_pro = QtWidgets.QLineEdit(self.centralwidget)
        self.nom_pro.setGeometry(QtCore.QRect(180, 70, 151, 21))
        self.nom_pro.setReadOnly(True)
        self.nom_pro.setObjectName("nom_pro")
        self.Lab = QtWidgets.QLineEdit(self.centralwidget)
        self.Lab.setGeometry(QtCore.QRect(340, 70, 113, 21))
        self.Lab.setReadOnly(True)
        self.Lab.setObjectName("Lab")
        self.p_unit = QtWidgets.QLineEdit(self.centralwidget)
        self.p_unit.setObjectName("p_unit")
        self.monto_t = QtWidgets.QLineEdit(self.centralwidget)
        self.monto_t.setGeometry(QtCore.QRect(650, 70, 113, 21))
        self.monto_t.setReadOnly(True)
        self.monto_t.setObjectName("monto_t")
        self.tabla_int = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_int.setEnabled(True)
        self.tabla_int.setGeometry(QtCore.QRect(20, 100, 801, 251))
        self.tabla_int.setMinimumSize(QtCore.QSize(651, 192))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.tabla_int.setFont(font)
        self.tabla_int.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabla_int.setAutoFillBackground(False)
        self.tabla_int.setAutoScroll(True)
        self.tabla_int.setAutoScrollMargin(16)
        self.tabla_int.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_int.setDragEnabled(False)
        self.tabla_int.setShowGrid(True)
        self.tabla_int.setWordWrap(True)
        self.tabla_int.setCornerButtonEnabled(True)
        self.tabla_int.setObjectName("tabla_int")
        self.tabla_int.setColumnCount(6)
        self.tabla_int.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tabla_int.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.tabla_int.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_int.setItem(9, 5, item)


        self.tabla_int.horizontalHeader().setVisible(False)
        self.tabla_int.horizontalHeader().setCascadingSectionResizes(True)
        self.tabla_int.horizontalHeader().setDefaultSectionSize(124)
        self.tabla_int.horizontalHeader().setHighlightSections(True)
        self.tabla_int.horizontalHeader().setMinimumSectionSize(20)
        self.tabla_int.horizontalHeader().setSortIndicatorShown(False)
        self.tabla_int.horizontalHeader().setStretchLastSection(False)
        self.tabla_int.verticalHeader().setCascadingSectionResizes(False)
        self.tabla_int.verticalHeader().setDefaultSectionSize(25)
        self.tabla_int.verticalHeader().setHighlightSections(True)
        self.tabla_int.verticalHeader().setMinimumSectionSize(100)
        self.tabla_int.verticalHeader().setSortIndicatorShown(False)
        self.boleta = QtWidgets.QTableWidget(self.centralwidget)
        self.boleta.setGeometry(QtCore.QRect(30, 400, 511, 271))
        self.boleta.setObjectName("boleta")
        self.boleta.setColumnCount(5)
        self.boleta.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        item.setText("1")
        self.boleta.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.boleta.setItem(7, 3, item)
        self.boleta.horizontalHeader().setDefaultSectionSize(100)
        self.boleta.horizontalHeader().setMinimumSectionSize(50)
        self.boleta.verticalHeader().setDefaultSectionSize(25)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 360, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(180, 20, 671, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 30, 20, 641))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 20, 31, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(590, 410, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(590, 440, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.bot_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.bot_agregar.setGeometry(QtCore.QRect(100, 60, 71, 31))
        self.bot_agregar.setObjectName("bot_agregar")
        self.bot_agregar.clicked.connect(lambda: self.modelo_principal.listar_productos(self.tabla_int))
        self.cod_bus = QtWidgets.QLineEdit(self.centralwidget)
        self.cod_bus.setGeometry(QtCore.QRect(20, 70, 71, 21))
        self.cod_bus.setText("")
        self.cod_bus.setAlignment(QtCore.Qt.AlignCenter)
        self.cod_bus.setObjectName("cod_bus")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(590, 470, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(590, 500, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(590, 530, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.fecha = QtWidgets.QLineEdit(self.centralwidget)
        self.fecha.setGeometry(QtCore.QRect(690, 410, 141, 21))
        self.fecha.setAcceptDrops(False)
        self.fecha.setReadOnly(True)
        self.fecha.setObjectName("fecha")
        today = date.today()
        self.fecha.setText(str(today))
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(460, 70, 81, 21))
        self.spinBox.setObjectName("spinBox")
        self.vendedor = QtWidgets.QLineEdit(self.centralwidget)
        self.vendedor.setGeometry(QtCore.QRect(690, 470, 141, 21))
        self.vendedor.setObjectName("vendedor")
        self.cliente = QtWidgets.QLineEdit(self.centralwidget)
        self.cliente.setGeometry(QtCore.QRect(690, 500, 141, 21))
        self.cliente.setReadOnly(False)
        self.cliente.setObjectName("cliente")
        self.turno = QtWidgets.QComboBox(self.centralwidget)
        self.turno.setGeometry(QtCore.QRect(690, 530, 141, 21))
        self.turno.setObjectName("turno")
        self.turno.addItem("")
        self.turno.addItem("")
        self.tipo_pago = QtWidgets.QComboBox(self.centralwidget)
        self.tipo_pago.setGeometry(QtCore.QRect(690, 440, 141, 21))
        self.tipo_pago.setObjectName("tipo_pago")
        self.tipo_pago.addItem("")
        self.tipo_pago.addItem("")
        self.generar_venta = QtWidgets.QPushButton(self.centralwidget)
        self.generar_venta.setGeometry(QtCore.QRect(590, 590, 241, 31))
        self.generar_venta.setObjectName("generar_venta")
        self.terminar = QtWidgets.QPushButton(self.centralwidget)
        self.terminar.setGeometry(QtCore.QRect(590, 630, 241, 31))
        self.terminar.setObjectName("terminar")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(590, 560, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.total_general = QtWidgets.QLineEdit(self.centralwidget)
        self.total_general.setGeometry(QtCore.QRect(690, 560, 91, 21))
        self.total_general.setReadOnly(True)
        self.total_general.setObjectName("total_general")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(1030, 40, 21, 251))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(520, 400, 41, 241))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(10, 710, 841, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(30, 640, 501, 31))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(210, 370, 641, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(840, 30, 20, 691))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(590, 670, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.cod_bus_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.cod_bus_2.setGeometry(QtCore.QRect(580, 690, 71, 21))
        self.cod_bus_2.setText("")
        self.cod_bus_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cod_bus_2.setObjectName("cod_bus_2")
        self.bot_agregar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bot_agregar_2.setGeometry(QtCore.QRect(660, 680, 71, 31))
        self.bot_agregar_2.setObjectName("bot_agregar_2")
        VENTANA.setCentralWidget(self.centralwidget)

        self.bot_agregar_2.clicked.connect(self.accion)

        self.retranslateUi(VENTANA)
        QtCore.QMetaObject.connectSlotsByName(VENTANA)

    def accion(self):
        for valor in range(0, 10):
            if  str(valor) == self.cod_bus.text():
                print(valor)
                product = self.registrar.getProduct(valor)
                print(product[4])
                self.nom_pro.setText(product[2])
                self.p_unit.setText(str(product[4]))
                self.Lab.setText(str(product[3]))
                cant = self.spinBox.text()
                monto_und = int(product[4]) * int(cant)
                if (int(cant) > 0):
                    self.monto_t.setText(str(monto_und) + ".00")
                else:
                    self.monto_t.setText(".00")
            else:
                print(f"{valor} No se encontro")

    def generar_venta(self):
        _translate = QtCore.QCoreApplication.translate
        producto = self.nom_pro.text()
        cantidad = self.spinBox.text()
        unidades = "und"
        precio_und = self.p_unit.text()
        importe = int(cantidad) * int(precio_und)
        escribir_base_datos(producto, cantidad, unidades, precio_und, str(importe))
        cnd_elem = elemtos_ventas()
        item = self.boleta.item(cnd_elem - 1, 0)
        item.setText(_translate("VENTANA", producto))
        item = self.boleta.item(cnd_elem - 1, 1)
        item.setText(_translate("VENTANA", cantidad))
        item = self.boleta.item(cnd_elem - 1, 2)
        item.setText(_translate("VENTANA", unidades))
        item = self.boleta.item(cnd_elem - 1, 3)
        item.setText(_translate("VENTANA", precio_und))
        item = self.boleta.item(cnd_elem - 1, 4)
        item.setText(_translate("VENTANA", str(importe) + '.00'))
        self.total_general.setText(str(monto_total(cnd_elem)) + '.00')

    def retranslateUi(self, VENTANA):
        _translate = QtCore.QCoreApplication.translate
        VENTANA.setWindowTitle(_translate("VENTANA", "MainWindow"))
        self.label.setText(_translate("VENTANA", "EXISTENCIAS"))
        self.label_2.setText(_translate("VENTANA", "Codigo"))
        self.label_3.setText(_translate("VENTANA", "Nombre Producto"))
        self.label_4.setText(_translate("VENTANA", "Existencias"))
        self.label_5.setText(_translate("VENTANA", "Cantidad"))
        self.label_6.setText(_translate("VENTANA", "P.Minorista"))
        self.label_7.setText(_translate("VENTANA", "Monto Total"))
        self.tabla_int.setSortingEnabled(False)
        item = self.tabla_int.verticalHeaderItem(0)
        item.setText(_translate("VENTANA", "1"))
        item = self.tabla_int.verticalHeaderItem(1)
        item.setText(_translate("VENTANA", "2"))
        item = self.tabla_int.verticalHeaderItem(2)
        item.setText(_translate("VENTANA", "3"))
        item = self.tabla_int.verticalHeaderItem(3)
        item.setText(_translate("VENTANA", "4"))
        item = self.tabla_int.verticalHeaderItem(4)
        item.setText(_translate("VENTANA", "5"))
        item = self.tabla_int.verticalHeaderItem(5)
        item.setText(_translate("VENTANA", "6"))
        item = self.tabla_int.verticalHeaderItem(6)
        item.setText(_translate("VENTANA", "7"))
        item = self.tabla_int.verticalHeaderItem(7)
        item.setText(_translate("VENTANA", "8"))
        item = self.tabla_int.verticalHeaderItem(8)
        item.setText(_translate("VENTANA", "9"))
        item = self.tabla_int.verticalHeaderItem(9)
        item.setText(_translate("VENTANA", "10"))
        item = self.tabla_int.horizontalHeaderItem(0)
        item.setText(_translate("VENTANA", "Codigo"))
        item = self.tabla_int.horizontalHeaderItem(1)
        item.setText(_translate("VENTANA", "Nombre Producto                        "))
        item = self.tabla_int.horizontalHeaderItem(2)
        item.setText(_translate("VENTANA", "Laboratorio"))
        item = self.tabla_int.horizontalHeaderItem(3)
        item.setText(_translate("VENTANA", "Cantidad"))
        item = self.tabla_int.horizontalHeaderItem(4)
        item.setText(_translate("VENTANA", "P.Unitario"))
        item = self.tabla_int.horizontalHeaderItem(5)
        item.setText(_translate("VENTANA", "Monto Total"))
        __sortingEnabled = self.tabla_int.isSortingEnabled()
        self.tabla_int.setSortingEnabled(False)
        item = self.tabla_int.item(0, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(0, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(0, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(0, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(0, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(0, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(1, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(2, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(3, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(4, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(5, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(6, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(7, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(8, 5)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 4)
        item.setText(_translate("VENTANA", "-"))
        item = self.tabla_int.item(9, 5)
        item.setText(_translate("VENTANA", "-"))
        self.tabla_int.setSortingEnabled(__sortingEnabled)
        item = self.boleta.verticalHeaderItem(1)
        item.setText(_translate("VENTANA", "2"))
        item = self.boleta.verticalHeaderItem(2)
        item.setText(_translate("VENTANA", "3"))
        item = self.boleta.verticalHeaderItem(3)
        item.setText(_translate("VENTANA", "4"))
        item = self.boleta.verticalHeaderItem(4)
        item.setText(_translate("VENTANA", "5"))
        item = self.boleta.verticalHeaderItem(5)
        item.setText(_translate("VENTANA", "6"))
        item = self.boleta.verticalHeaderItem(6)
        item.setText(_translate("VENTANA", "7"))
        item = self.boleta.verticalHeaderItem(7)
        item.setText(_translate("VENTANA", "8"))
        item = self.boleta.horizontalHeaderItem(0)
        item.setText(_translate("VENTANA", "Producto"))
        item = self.boleta.horizontalHeaderItem(1)
        item.setText(_translate("VENTANA", "Cantidad"))
        item = self.boleta.horizontalHeaderItem(2)
        item.setText(_translate("VENTANA", "P.Unit"))
        item = self.boleta.horizontalHeaderItem(3)
        item.setText(_translate("VENTANA", "Deposito"))
        item = self.boleta.horizontalHeaderItem(4)
        item.setText(_translate("VENTANA", "Pendiente"))
        __sortingEnabled = self.boleta.isSortingEnabled()
        self.boleta.setSortingEnabled(False)
        item = self.boleta.item(0, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(0, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(0, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(0, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(1, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(1, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(1, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(1, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(2, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(2, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(2, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(2, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(3, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(3, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(3, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(3, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(4, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(4, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(4, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(4, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(5, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(5, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(5, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(5, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(6, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(6, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(6, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(6, 3)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(7, 0)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(7, 1)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(7, 2)
        item.setText(_translate("VENTANA", "-"))
        item = self.boleta.item(7, 3)
        item.setText(_translate("VENTANA", "-"))
        self.boleta.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("VENTANA", "Detalle de Venta"))
        self.label_9.setText(_translate("VENTANA", "Fecha"))
        self.label_12.setText(_translate("VENTANA", "Pago"))
        self.bot_agregar.setText(_translate("VENTANA", "Cotizar"))
        self.cod_bus.setPlaceholderText(_translate("VENTANA", "ffff"))
        self.label_13.setText(_translate("VENTANA", "Vendedor"))
        self.label_14.setText(_translate("VENTANA", "Cliente"))
        self.label_15.setText(_translate("VENTANA", "Turno"))
        self.turno.setItemText(0, _translate("VENTANA", "Mañana"))
        self.turno.setItemText(1, _translate("VENTANA", "Tarde"))
        self.tipo_pago.setItemText(0, _translate("VENTANA", "Efectivo"))
        self.tipo_pago.setItemText(1, _translate("VENTANA", "Tarjeta"))
        self.generar_venta.setText(_translate("VENTANA", "Generar VENTA"))
        self.terminar.setText(_translate("VENTANA", "Guardar"))
        self.label_21.setText(_translate("VENTANA", "Total"))
        self.label_10.setText(_translate("VENTANA", "Codigo"))
        self.cod_bus_2.setPlaceholderText(_translate("VENTANA", "ffff"))
        self.bot_agregar_2.setText(_translate("VENTANA", "Agregar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VENTANA = QtWidgets.QMainWindow()
    ui = Ui_VENTANA()
    ui.setupUi(VENTANA)
    VENTANA.show()
    sys.exit(app.exec_())

